import Fastify from 'fastify';
import postgres from 'postgres';
import { fastifyTRPCPlugin, type FastifyTRPCPluginOptions } from '@trpc/server/adapters/fastify';
import { createEdgeContext, mergeRouters, verifyServiceHeaders } from '@intafaced/contracts';
import { JetStreamEventBus } from '@intafaced/events';
import { env } from './env.js';
import { AuthService } from './auth/auth-service.js';
import { PlaceDoor } from './auth/place-door.js';
import { registerApiKeyOwnershipRoute } from './auth/api-key-ownership-route.js';
import { assertProdTotpKey } from './auth/totp-crypto.js';
import { RankService } from './rank/rank-service.js';
import { ReferralService } from './affiliates/referral-service.js';
import { ShareService } from './affiliates/share-service.js';
import { FreezeService } from './affiliates/freeze-service.js';
import { SqlAccrualStore } from './affiliates/accrual-store.js';
import { parseAccrualTierLawJson } from './affiliates/commission-rate-law.js';
import { parseDmaHierarchyLawJson } from './orgs/dma-hierarchy.js';
import { createLedgerClient } from './ledger-client.js';
import { assertArgon2Available, argon2Available } from './auth/passwords.js';
import { createIdentityRouter } from './router.js';
import { createApiKeyIpRouter } from './api-key-ip-router.js';
import { createApiKeyOriginRouter } from './api-key-origin-router.js';
import { createApiKeyAccountRouter } from './api-key-account-router.js';
import { createApiKeyRotateRouter } from './api-key-rotate-router.js';
import { createApiKeyExpireRouter } from './api-key-expire-router.js';
import { createApiKeyRevokeAllRouter } from './api-key-revoke-all-router.js';
import { createSessionRevokeAllRouter } from './session-revoke-all-router.js';
import { createSessionRevokeRouter } from './session-revoke-router.js';
import { createListSessionsRouter } from './list-sessions-router.js';
import { createPanicRevokeRouter } from './panic-revoke-router.js';
import { createApiKeyProductRouter } from './api-key-product-router.js';
import { createDisableUserRouter } from './disable-user-router.js';
import { createOrgRouter } from './org-router.js';
import { createEnrollPasskeyRouter } from './enroll-passkey-router.js';
import { createVerifyPasskeyRouter } from './verify-passkey-router.js';
import { createUnenrollPasskeyRouter } from './unenroll-passkey-router.js';
import { installDisabledMintRefuse } from './auth/disable-user.js';
import { installPasskeyMintRefuse } from './auth/mint-api-key-passkey.js';
import { installFourEyes } from './auth/four-eyes.js';
import { installApiKeyIpExchange, requestIpAls } from './auth/auth-service-ip.js';
import { installApiKeyProductExchange, requestProductAls } from './auth/auth-service-product.js';
import { installApiKeyAccountExchange } from './auth/bind-api-key-account.js';
import { bootKycVault } from './kyc/boot-vault.js';
import { SqlWaitlistStore } from './waitlist/waitlist-store.js';
import { WaitlistService } from './waitlist/waitlist-service.js';
import { registerAffiliateProducerAccrue } from './affiliates/producer-accrue.js';
import { registerAffiliateProducerPayout } from './affiliates/producer-payout.js';
import { createNavigatorSessionStore } from './agents/navigator-session-store.js';
import { registerNavigatorSessionRoutes } from './agents/navigator-session-routes.js';
import { subscribeBlueprintProfileEvents, subscribeXpEvents } from './events.js';
import { registerProcessHooks, startTelemetry } from '@intafaced/telemetry';
