apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: intafaced-prom
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: intafaced-tempo

  - name: Tempo
    type: tempo
    uid: intafaced-tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToMetrics:
        datasourceUid: intafaced-prom
      serviceMap:
        datasourceUid: intafaced-prom
