import { TRPCError } from '@trpc/server';
import { z } from 'zod';
import { publicProcedure, router, scopedProcedure } from '@intafaced/contracts';
import { SealedHouseTenantRegistry, type TenantDescribe, type TenantRefusal } from '@intafaced/execution-house-tenant';
import type { CaptureLake } from '@intafaced/venue-adapter';
import { cancelOmsOrder, type OmsCancelFn } from './oms-cancel.js';
import { killInFlightExecution } from './oms-kill.js';
import { drainInFlightAlgo } from './oms-drain.js';
import { cancelRemainingParentChildren } from './oms-cancel-remaining.js';
import { attributeChildFillsToParent } from './oms-attribute.js';
import { repairFailedHedgeChild } from './oms-repair-hedge.js';
import { retryFailedHedgeChild } from './oms-retry-hedge.js';
import { listFailedHedgeChildren } from './oms-failed-hedges.js';
import { listLiveEmsChildren } from './oms-live-children.js';
import { InMemoryAlgoPauseStore, pauseInFlightAlgo, type AlgoPauseStore } from './oms-pause.js';
import { resumeInFlightAlgo } from './oms-resume.js';
import { resolveMatchingVenueHalt, type MatchingVenueHaltPort } from './oms-matching-venue-halt.js';
import { InMemoryApprovedAlgoParentStore, startApprovedAlgoParent, type ApprovedAlgoParentStore, type AlgoJobsGate } from './oms-start.js';
import { startBasketParent } from './oms-basket-start.js';
import { stopRunningAlgoParent } from './oms-stop.js';
import { undeployStoppedAlgoParent } from './oms-undeploy.js';
import { undeployDrainStoppedAlgoParent } from './oms-undeploy-drain.js';
import { expireAlgoParent } from './oms-expire.js';
import { releaseExpiredParentResidual } from './oms-release-residual.js';
import { paperRunAlgoParent } from './oms-paper.js';
import { promotePaperParentToLive } from './oms-promote.js';
import { stageApprovedParent } from './oms-stage.js';
import { releaseStagedParentToLive } from './oms-release.js';
import { abandonStagedParent } from './oms-abandon.js';
import { sliceLiveAlgoParent } from './oms-slice.js';
import { scheduleSliceLiveAlgoParent } from './oms-schedule-slice.js';
import { listUnattendedLiveParents } from './oms-unattended.js';
import { listUnconfirmedChildFills } from './oms-unconfirmed.js';
import { assignOrphanedChildFill, listOrphanedChildFills } from './oms-assign.js';
import { killUnattendedLiveParent } from './oms-unattended-kill.js';
import { killLiveAlgoParent } from './oms-kill-parent.js';
import { claimLiveAlgoParent, readLiveAlgoParentOwnership, unclaimLiveAlgoParent } from './oms-claim.js';
import { acceptLiveAlgoParentPass, passLiveAlgoParent, rejectLiveAlgoParentPass, timeoutLiveAlgoParentPass } from './oms-pass.js';
import { shiftLiveAlgoParent } from './oms-shift.js';
import { confirmChildFill, InMemoryFillConfirmStore, readChildFillConfirmation, type FillConfirmStore } from './oms-fill-confirm.js';
import { InMemoryManualFillStore, recordManualChildFill, type ManualFillStore } from './oms-manual-fill.js';
import { assignChildFill, correctChildFill, InMemoryFillAssignStore, type FillAssignStore } from './oms-fill-assign.js';
import { approveAlgoParent } from './oms-approve.js';
import { executeOmsRoute, type OmsSubmitFn } from './oms-execute.js';
import { fetchOmsOrder, type OmsFetchFn } from './oms-fetch.js';
import { listOmsOpenOrders, type OmsOpenOrdersFn } from './oms-open-orders.js';
import { observeOmsBalances, type OmsBalancesFn } from './oms-balances.js';
import { observeOmsPositions, type OmsPositionsFn } from './oms-positions.js';
import { observeOmsBorrow, type OmsBorrowFn } from './oms-borrow.js';
import { observeOmsFunding, type OmsFundingFn } from './oms-funding.js';
import { observeOmsLatency, type OmsLatencyFn } from './oms-latency.js';
import { observeOmsMarkets, type OmsMarketsFn } from './oms-markets.js';
import { observeOmsRails, type OmsRailsFn } from './oms-rails.js';
import { observeOmsSnapshot, type OmsSnapshotFn } from './oms-snapshot.js';
import { scanOmsExternalArb } from './oms-arbitrage.js';
import { planOmsArbAtomicLegs } from './oms-arb-plan-legs.js';
import { executeOmsArbAtomicLegs } from './oms-arb-execute-legs.js';
import { describeExecutionSpine } from './oms-spine.js';
import { planOmsExternalMmHedge, quoteOmsExternalMm } from './oms-market-making.js';
import { planOmsRoute } from './oms-plan.js';
import { runTcaRun, TCA_BENCHMARK_CLASSES } from './oms-tca.js';
import { runTcaForParent } from './oms-tca-parent.js';
import { recordMarkoutsForParent } from './oms-tca-markouts.js';
import { withExecutionSpan } from './tracing.js';
import type { EmsOrderStore } from './oms-ems-store.js';
