import { TRPCError } from '@trpc/server';
import { z } from 'zod';
import { publicProcedure, router, scopedProcedure } from '@intafaced/contracts';
import { SealedHouseTenantRegistry, type TenantDescribe, type TenantRefusal } from '@intafaced/execution-house-tenant';
import type { CaptureLake } from '@intafaced/venue-adapter';
import { cancelOmsOrder, type OmsCancelFn } from './oms-cancel.js';
import { killInFlightExecution } from './oms-kill.js';
import { drainInFlightAlgo } from './oms-drain.js';
import { cancelRemainingParentChildren } from './oms-cancel-remaining.js';
import { attributeChildFillsToParent } from './oms-attribute.js';
import { InMemoryAlgoPauseStore, pauseInFlightAlgo, type AlgoPauseStore } from './oms-pause.js';
import { resumeInFlightAlgo } from './oms-resume.js';
import { InMemoryApprovedAlgoParentStore, startApprovedAlgoParent, type ApprovedAlgoParentStore, type AlgoJobsGate } from './oms-start.js';
import { stopRunningAlgoParent } from './oms-stop.js';
import { executeOmsRoute, type OmsSubmitFn } from './oms-execute.js';
import { fetchOmsOrder, type OmsFetchFn } from './oms-fetch.js';
import { listOmsOpenOrders, type OmsOpenOrdersFn } from './oms-open-orders.js';
import { observeOmsBalances, type OmsBalancesFn } from './oms-balances.js';
import { observeOmsPositions, type OmsPositionsFn } from './oms-positions.js';
import { observeOmsBorrow, type OmsBorrowFn } from './oms-borrow.js';
import { observeOmsFunding, type OmsFundingFn } from './oms-funding.js';
import { observeOmsLatency, type OmsLatencyFn } from './oms-latency.js';
import { observeOmsMarkets, type OmsMarketsFn } from './oms-markets.js';
import { observeOmsRails, type OmsRailsFn } from './oms-rails.js';
import { observeOmsSnapshot, type OmsSnapshotFn } from './oms-snapshot.js';
import { scanOmsExternalArb } from './oms-arbitrage.js';
import { planOmsArbAtomicLegs } from './oms-arb-plan-legs.js';
import { executeOmsArbAtomicLegs } from './oms-arb-execute-legs.js';
import { describeExecutionSpine } from './oms-spine.js';
import { planOmsExternalMmHedge, quoteOmsExternalMm } from './oms-market-making.js';
import { planOmsRoute } from './oms-plan.js';
import { runTcaRun, TCA_BENCHMARK_CLASSES } from './oms-tca.js';
import { runTcaForParent } from './oms-tca-parent.js';
import { recordMarkoutsForParent } from './oms-tca-markouts.js';
import { withExecutionSpan } from './tracing.js';
import type { EmsOrderStore } from './oms-ems-store.js';

const tenantIdInput = z.object({ tenantId: z.string().min(1).max(128) });
